version: '3.8'

services:
  # ==========================================
  # INFRASTRUCTURE SERVICES
  # ==========================================
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin_secret
      POSTGRES_DB: bank_db
    ports:
      - "55432:5432"
    networks:
      - backend-network
    volumes:
      - pg-data:/var/lib/postgresql/data

  mongodb:
    image: mongo:8.0-noble
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongo_admin
      MONGO_INITDB_ROOT_PASSWORD: mongo_secret
    ports:
      - "27017:27017"
    networks:
      - backend-network
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7-alpine
    command: redis-server --requirepass redis_secret
    ports:
      - "6379:6379"
    networks:
      - backend-network

  rabbitmq:
    image: rabbitmq:3-management-alpine
    environment:
      RABBITMQ_DEFAULT_USER: mq_admin
      RABBITMQ_DEFAULT_PASS: mq_secret
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI
    networks:
      - backend-network

  # ==========================================
  # APPLICATION MICROSERVICES
  # ==========================================
  api-gateway:
    build: ./services/api-gateway
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - AUTH_SERVICE_URL=http://auth-service:4001
      - ACCOUNT_SERVICE_URL=http://account-service:4002
      - TRANSACTION_SERVICE_URL=http://transaction-service:4003
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis_secret
    depends_on:
      - redis
    networks:
      - backend-network

  auth-service:
    build: ./services/auth-service
    environment:
      - PORT=4001
      - DB_HOST=postgres
      - DB_USER=admin
      - DB_PASSWORD=admin_secret
      - DB_NAME=bank_db
      - JWT_SECRET=super_secret_jwt_key
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis_secret
    depends_on:
      - postgres
      - redis
    networks:
      - backend-network

  account-service:
    build: ./services/account-service
    environment:
      - PORT=4002
      - DB_HOST=postgres
      - DB_USER=admin
      - DB_PASSWORD=admin_secret
      - DB_NAME=bank_db
      - JWT_SECRET=super_secret_jwt_key
      - MONGO_URI=mongodb://mongo_admin:mongo_secret@mongodb:27017/ledger_audit?authSource=admin
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis_secret
    depends_on:
      - postgres
      - mongodb
      - redis
    networks:
      - backend-network

  transaction-service:
    build: ./services/transaction-service
    environment:
      - PORT=4003
      - ACCOUNT_SERVICE_URL=http://account-service:4002
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=mq_admin
      - RABBITMQ_PASS=mq_secret
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redis_secret
      - EXCHANGE_NAME=transaction_exchange
      - QUEUE_NAME=payment_queue
      - ROUTING_KEY=payment.process
      - DLX_NAME=transaction_dlx
      - DLQ_NAME=payment_dlq
      - DLQ_ROUTING_KEY=payment.dead_letter
      - RTX_NAME=transaction_retry_exchange
      - RTQ_NAME=payment_retry_queue
      - RTQ_ROUTING_KEY=payment.retry
      - JWT_SECRET=super_secret_jwt_key
    depends_on:
      - rabbitmq
      - redis
      - account-service
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge

volumes:
  pg-data:
  mongo-data: